### ISSUE TITLE
Instruction inconsistancy

### ISSUE THREAD

**Issue by henridb** [inQWIRE/SQIR#3]
Hi,
I noticed that your instruction on the method to run the optimizer is different in `VOQC/Readme.md` and in `VOQC/benchmarks/README.md`.
In particular, in the first file you give the command
`dune exec --root ../extraction ./voqc.exe -i <prog> -o <out>` 
and in the second one you give the command  
`dune exec --root ../extraction -- ./voqc.exe -i <prog> -o <out>`
I believe the latest is the right one since without the double dash, dune returns the error 
```
unknown option `-i'.
unknown option `-o'.
```

**Comment by khieta** [comment]
Thanks for pointing this out!
